import {afterEach,beforeEach,describe,expect,it} from 'vitest';
import {GatewayStore} from '../src/persistence/index.js';
import {DomainBus} from '../src/core/events.js';
import {AdapterRuntime} from '../src/adapters/runtime.js';
import {MockAdapter} from '../src/adapters/mock/index.js';
import {DeviceRegistry} from '../src/core/devices/index.js';
import {GroupService} from '../src/core/groups/index.js';
import {OperationService} from '../src/core/operations/index.js';
import {SceneService} from '../src/core/scenes/index.js';
import {EffectService,EFFECT_IDS} from '../src/core/effects/index.js';

describe('command execution against real mock and SQLite',()=>{
 let store:GatewayStore,bus:DomainBus,runtime:AdapterRuntime,registry:DeviceRegistry,groups:GroupService,operations:OperationService,scenes:SceneService,effects:EffectService;
 const id=(model:string)=>registry.list().find(d=>d.model===model)!.id;
 beforeEach(async()=>{store=new GatewayStore(':memory:');bus=new DomainBus(store.gatewayId);runtime=new AdapterRuntime(bus);runtime.register(new MockAdapter());registry=new DeviceRegistry(store,runtime,bus);groups=new GroupService(store,registry,bus);operations=new OperationService(store,registry,runtime,bus);operations.setGroupResolver(id=>groups.get(id).deviceIds);scenes=new SceneService(store,groups,operations,bus);effects=new EffectService(store,registry,runtime,operations,bus);await runtime.connect('mock');await registry.discover('mock');});
 afterEach(async()=>{await effects.close();await operations.drain();groups.close();await runtime.close();await registry.close();store.close();});
 it.each(['white','temperature'])('rejects RGB on %s with exact capability detail',model=>{expect(()=>operations.submitCommand({type:'device',id:id(model)},{rgb:{r:255,g:0,b:0}},{requestId:'req-test'})).toThrowError(expect.objectContaining({statusCode:422,detail:{code:'capability_mismatch',message:'Device does not support rgb',requestId:'req-test',details:[{path:'/state/rgb',code:'unsupported_capability',message:'Required capability rgb is absent',deviceId:id(model),capability:'rgb'}]}}));expect(store.listOperations()).toHaveLength(0);});
 it('refuses known offline singleton before queueing',()=>{expect(()=>operations.submitCommand({type:'device',id:id('offline')},{power:true})).toThrowError(expect.objectContaining({statusCode:409,code:'device_offline'}));expect(store.listOperations()).toHaveLength(0);});
 it('persists queued then immutable terminal partial group outcomes',async()=>{const group=groups.create('mixed',[id('rgb'),id('offline')]);const admission=operations.submitCommand({type:'group',id:group.id},{power:true});expect(admission.status).toBe('queued');expect(admission.results).toEqual([]);const done=await operations.wait(admission.id);expect(done.status).toBe('partial');expect(done.results).toEqual([expect.objectContaining({deviceId:id('rgb'),status:'succeeded',confirmation:'observed',transport:'mock',fallback:null,fieldResults:[{path:'/power',status:'applied'}]}),{deviceId:id('offline'),status:'failed',confirmation:'unconfirmed',transport:null,fallback:null,fieldResults:[],warnings:[],error:expect.objectContaining({code:'device_offline'})}]);expect(operations.get(done.id)).toEqual(done);expect(()=>store.saveOperation({...done,status:'succeeded'})).toThrow();});
 it('rejects malformed scene state and transition at definition time',()=>{expect(()=>scenes.create('invalid',[{target:{type:'device',id:id('rgb')},state:{rgb:{r:999,g:0,b:0}}}])).toThrowError(expect.objectContaining({code:'validation_error'}));expect(()=>scenes.create('invalid transition',[{target:{type:'device',id:id('rgb')},state:{power:true},transitionMs:-1}])).toThrowError(expect.objectContaining({code:'validation_error'}));});
 it('reports scene transition omission only after explicit opt-in',async()=>{const scene=scenes.create('reading',[{target:{type:'device',id:id('rgb')},state:{brightness:65},transitionMs:500}]);expect(()=>scenes.activate(scene.id)).toThrowError(expect.objectContaining({code:'no_eligible_targets'}));const done=await operations.wait(scenes.activate(scene.id,{allowDegraded:true}).id);expect(done.status).toBe('partial');expect(done.results[0]).toMatchObject({status:'degraded',warnings:[{code:'unsupported_transition',requested:'transitionMs=500',applied:'transition omitted; immediate application'}],fieldResults:[{path:'/brightness',status:'applied'},{path:'/transitionMs',status:'omitted',reason:'unsupported_transition'}]});});
 it('never degrades requested RGB into white output',async()=>{const group=groups.create('color mix',[id('rgb'),id('white')]);const scene=scenes.create('color',[{target:{type:'group',id:group.id},state:{rgb:{r:0,g:0,b:255}},transitionMs:300}]);const done=await operations.wait(scenes.activate(scene.id,{allowDegraded:true}).id);expect(done.status).toBe('partial');expect(done.results.find(r=>r.deviceId===id('white'))).toMatchObject({status:'failed',error:{code:'capability_mismatch',details:[{capability:'rgb'}]},transport:null,fieldResults:[]});});
 it('reserves static effect targets until an idempotent stop',async()=>{const start=effects.start(EFFECT_IDS.static,{type:'device',id:id('white')},{state:{brightness:20}});expect(()=>operations.submitCommand({type:'device',id:id('white')},{power:true})).toThrowError(expect.objectContaining({code:'effect_conflict'}));expect((await operations.wait(start.id)).status).toBe('succeeded');const stop=effects.stop(start.effectRunId!);await operations.wait(stop.id);expect(effects.getRun(start.effectRunId!).status).toBe('stopped');expect((await operations.wait(effects.stop(start.effectRunId!).id)).status).toBe('succeeded');expect((await operations.wait(operations.submitCommand({type:'device',id:id('white')},{power:true}).id)).status).toBe('succeeded');});
 it('pulse schedules frames, exposes cadence, and stops future frames',async()=>{const started=effects.start(EFFECT_IDS.pulse,{type:'device',id:id('white')},{minimum:10,maximum:80,periodMs:200});await operations.wait(started.id);const before=registry.get(id('white')).revision;await new Promise(resolve=>setTimeout(resolve,150));expect(registry.get(id('white')).revision).toBeGreaterThan(before);expect(effects.getRun(started.effectRunId!).deviceExecutions[0]).toMatchObject({status:'running',effectiveIntervalMs:100});await operations.wait(effects.stop(started.effectRunId!).id);const stoppedRevision=registry.get(id('white')).revision;await new Promise(resolve=>setTimeout(resolve,150));expect(registry.get(id('white')).revision).toBe(stoppedRevision);});

});
