export type * from './model.js';
export { GatewayError } from './errors.js';
export type { ErrorDetail, ValidationDetail } from './errors.js';
export { DomainBus } from './events.js';
export type { DomainData, DomainEvent } from './events.js';
export { DeviceRegistry } from './devices/index.js';
export { validateState, validateSyntax } from './capabilities/index.js';
export { OperationService } from './operations/index.js';
export type { SubmitOptions } from './operations/index.js';
export type { Command, DeviceResult, Operation, OperationStatus, Target } from './operations/types.js';
export { RoomService } from './rooms/index.js';
export type { Room, AggregateState } from './rooms/index.js';
export { GroupService } from './groups/index.js';
export type { Group } from './groups/index.js';
export { SceneService } from './scenes/index.js';
export type { Scene, SceneEntry } from './scenes/index.js';
export { EffectService, EFFECT_IDS } from './effects/index.js';
export type { Effect, EffectRun } from './effects/index.js';
